# Basic Exercise

# Problem 1

In [6]:
import numpy as np

vector = np.arange(0, 8 + 1, 1)

print("Original Vector: {0}".format(vector))
print("Reverse Vector: {0}".format(vector[::-1]))
print("Reshaped 3x3 Matrix: \n{0}".format(np.reshape(vector, (3,3))))

Original Vector: [0 1 2 3 4 5 6 7 8]
Reverse Vector: [8 7 6 5 4 3 2 1 0]
Reshaped 3x3 Matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Problem 2

In [17]:
import numpy as np

id_matrix = np.eye(4)

print("Identity Matrix: \n{0}\n".format(id_matrix))
print("Non-Zero Elements Are: {0}".format(list(zip(*np.nonzero(id_matrix)))))

Identity Matrix: 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Non-Zero Elements Are: [(0, 0), (1, 1), (2, 2), (3, 3)]


# Problem 3

In [24]:
import numpy as np

number = int(input("Enter A Number: ") or '8')

matrix = np.empty((3,3), dtype=float)
matrix[:, :] = number
print("The 3x3 Matrix Containing The User Input Number Is: \n{0}".format(matrix))

Enter A Number: 
The 3x3 Matrix Containing The User Input Number Is: 
[[ 8.  8.  8.]
 [ 8.  8.  8.]
 [ 8.  8.  8.]]


# Problem 4

In [40]:
import numpy as np

matrix = 100 * np.random.rand(2, 2)
print("The Randomly Generated 2x2 Matrix Is: \n{0}".format(matrix))

The Randomly Generated 2x2 Matrix Is: 
[[ 62.59177838  91.97235879]
 [ 44.77750919  92.80274903]]


# Problem 5

In [55]:
import numpy as np

matrix_1 = np.zeros((5, 5))
for i in range(0, matrix_1[0, :].size):
    matrix_1[i, i - 1] = i

matrix_2 = np.zeros((4, 4))
for i in range(0, matrix_2[0, :].size):
    for j in range(0, matrix_2[:, 0].size):
        if int((i + j) % 2) == 1:
            matrix_2[i, j] = 1
        
print("The 1st Patterned Matrix Is: \n{0}".format(matrix_1))
print("The 2nd Patterned Matrix Is: \n{0}".format(matrix_2))

The 1st Patterned Matrix Is: 
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
The 2nd Patterned Matrix Is: 
[[ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]]


# Problem 6

In [86]:
import numpy as np
from numpy.linalg import matrix_rank

matrix = np.eye(3)
print(matrix)
print(matrix_rank(matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
3


# Problem 7

In [85]:
import numpy as np
array_1 = 3 * np.arange(3, 8, 1)

array_2 = array_1
for index in range(0, len(array_1) - 1):
    array_2 = np.insert(array_2, 4 * index + 1, (0, 0, 0))
# array_2 = np.insert(array_1, list(range(1, len(array_1) - 1)), [(0, 0, 0)])

print("The Original Array Is: {0}".format(array_1))
print("The Modified Array Is: {0}".format(array_2))

The Original Array Is: [ 9 12 15 18 21]
The Modified Array Is: [ 9  0  0  0 12  0  0  0 15  0  0  0 18  0  0  0 21]


# Problem 8

In [46]:
matrix = 10 * np.random.rand(5, 5)
matrix = matrix.astype(np.int64)
print("Original Matrix: \n{0}".format(matrix))
print("Matrix Excluding First & Last Row: \n{0}".format(matrix[1:-1, :]))
print("Matrix Excluding First & Last Columns: \n{0}".format(matrix[:, 1:-1]))


Original Matrix: 
[[9 0 9 1 6]
 [2 7 4 6 8]
 [3 7 5 3 1]
 [1 5 6 2 7]
 [1 1 1 0 0]]
Matrix Excluding First & Last Row: 
[[2 7 4 6 8]
 [3 7 5 3 1]
 [1 5 6 2 7]]
Matrix Excluding First & Last Columns: 
[[0 9 1]
 [7 4 6]
 [7 5 3]
 [5 6 2]
 [1 1 0]]
